docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - Messages:
            - "Intro and Usage": message/intro.md
            - "Attachments": message/attachments.md
            - "Character Sets": message/character-sets.md
        - Transports:
            - Usage: transport/intro.md
            - SMTP:
                - "SMTP Options": transport/smtp-options.md
                - "Sending multiple messages": transport/smtp-multiple-send.md
                - Authentication: transport/smtp-authentication.md
            - "File Transport Options": transport/file-options.md
        - "Reading and Storing Mail": read.md
site_name: laminas-mail
site_description: laminas-mail
repo_url: 'https://github.com/laminas/laminas-mail'
